// Generated by tools/export-tokens.mjs — do not edit by hand.
// Source: app/globals.css, lib/constants.ts, lib/legibility.ts
// Regenerate with: npm run tokens:ios

import SwiftUI

/// The web app's design tokens, verbatim. CSS pixels map 1:1 to iOS points.
public enum Tokens {
    // MARK: - Color

    public static let ink = Color(red: 0.0431, green: 0.0431, blue: 0.0471)
    public static let paper = Color(red: 1.0000, green: 1.0000, blue: 1.0000)
    public static let accent = Color(red: 1.0000, green: 0.7922, blue: 0.1569)
    public static let blue = Color(red: 0.1137, green: 0.4353, blue: 0.9490)
    public static let blueDeep = Color(red: 0.0431, green: 0.2275, blue: 0.5608)
    public static let bluePale = Color(red: 0.9333, green: 0.9569, blue: 1.0000)
    public static let blueLine = Color(red: 0.8431, green: 0.8980, blue: 1.0000)
    public static let red = Color(red: 0.9412, green: 0.2824, blue: 0.2431)
    public static let redDeep = Color(red: 0.7765, green: 0.1843, blue: 0.1490)
    public static let green = Color(red: 0.0431, green: 0.5608, blue: 0.4157)
    public static let greenPale = Color(red: 0.9059, green: 0.9647, blue: 0.9333)
    public static let cream = Color(red: 0.9569, green: 0.9333, blue: 0.8627)
    public static let pink = Color(red: 0.9765, green: 0.6588, blue: 0.7059)
    public static let dark1 = Color(red: 0.0784, green: 0.0784, blue: 0.0941)
    public static let dark2 = Color(red: 0.0863, green: 0.0863, blue: 0.1020)
    public static let dark3 = Color(red: 0.0902, green: 0.0902, blue: 0.1059)
    public static let darkHover = Color(red: 0.1333, green: 0.1333, blue: 0.1647)
    public static let sand1 = Color(red: 0.9608, green: 0.9569, blue: 0.9412)
    public static let sand2 = Color(red: 0.9490, green: 0.9451, blue: 0.9255)
    public static let sand3 = Color(red: 0.9255, green: 0.9176, blue: 0.8941)
    public static let sand4 = Color(red: 0.8902, green: 0.8863, blue: 0.8627)
    public static let sandHover = Color(red: 0.9373, green: 0.9333, blue: 0.9137)
    public static let muted1 = Color(red: 0.4275, green: 0.4275, blue: 0.4471)
    public static let muted2 = Color(red: 0.5412, green: 0.5412, blue: 0.5608)
    public static let muted3 = Color(red: 0.6627, green: 0.6627, blue: 0.6824)
    public static let muted4 = Color(red: 0.7412, green: 0.7412, blue: 0.7686)
    public static let muted5 = Color(red: 0.7529, green: 0.7490, blue: 0.7294)
    public static let line1 = Color(red: 0.9490, green: 0.9451, blue: 0.9255)
    public static let line2 = Color(red: 0.9569, green: 0.9529, blue: 0.9333)
    public static let line3 = Color(red: 0.9255, green: 0.9216, blue: 0.8980)
    public static let line4 = Color(red: 0.9059, green: 0.9020, blue: 0.8784)

    // MARK: - Motion

    /// Durations come from the call site because CSS carries them on each declaration,
    /// not on the easing token.
    public static func easeOut(_ duration: Double) -> Animation {
        .timingCurve(0.2, 0.8, 0.2, 1, duration: duration)
    }
    public static func easeSpring(_ duration: Double) -> Animation {
        .timingCurve(0.16, 1, 0.3, 1, duration: duration)
    }

    /// Literal curves used outside the two named tokens.
    public static func dealCurve(_ duration: Double) -> Animation {
        .timingCurve(0.2, 0.9, 0.22, 1, duration: duration)
    }

    public static func flipCurve(_ duration: Double) -> Animation {
        .timingCurve(0.22, 1, 0.28, 1, duration: duration)
    }

    // MARK: - Layout

    public static let appMaxW: CGFloat = 480
    public static let railW: CGFloat = 76
    public static let paneGap: CGFloat = 20
    public static let contentMax: CGFloat = 720

    // MARK: - Card geometry

    /// The art engine is authored against this box; every size scales off the width.
    public static let cardW: CGFloat = 320
    public static let cardH: CGFloat = 196
    public static let cardR: CGFloat = 22
    public static let deckStep: CGFloat = 334
    public static let deckOrigin: CGFloat = 22

    // MARK: - Card palettes

    public static let palettes: [(base: Color, accent: Color)] = [
        (Color(red: 1.0000, green: 0.7922, blue: 0.1569), Color(red: 0.0431, green: 0.0431, blue: 0.0471)),
        (Color(red: 0.1137, green: 0.4353, blue: 0.9490), Color(red: 0.9569, green: 0.9333, blue: 0.8627)),
        (Color(red: 0.9569, green: 0.9333, blue: 0.8627), Color(red: 0.9412, green: 0.2824, blue: 0.2431)),
        (Color(red: 0.9765, green: 0.6588, blue: 0.7059), Color(red: 0.9412, green: 0.2824, blue: 0.2431)),
        (Color(red: 0.0863, green: 0.0863, blue: 0.1020), Color(red: 1.0000, green: 0.7922, blue: 0.1569)),
        (Color(red: 0.0431, green: 0.5608, blue: 0.4157), Color(red: 0.9569, green: 0.9333, blue: 0.8627)),
    ]

    // MARK: - Category colors

    public static let categoryColors: [String: Color] = [
        "Food": Color(red: 0.9412, green: 0.2824, blue: 0.2431),
        "Transport": Color(red: 0.1137, green: 0.4353, blue: 0.9490),
        "Bills": Color(red: 0.4863, green: 0.2275, blue: 0.9294),
        "Groceries": Color(red: 0.0431, green: 0.5608, blue: 0.4157),
        "Shopping": Color(red: 1.0000, green: 0.7922, blue: 0.1569),
        "Load": Color(red: 0.9255, green: 0.2824, blue: 0.6000),
        "Health": Color(red: 0.0314, green: 0.5686, blue: 0.6980),
        "Fun": Color(red: 0.9765, green: 0.4510, blue: 0.0863),
    ]

    // MARK: - Legibility tuner tables

    /// Scrim ladder — alpha of the wash behind card text.
    public static let scrim: [String: Double] = [
        "off": 0,
        "soft": 0.32,
        "strong": 0.55,
        "veil": 0.5,
    ]

    /// Pattern amplitudes the tuner damps through, strongest first.
    public static let amplitudes: [Double] = [1, 0.8, 0.62, 0.48, 0.36, 0.26, 0.18, 0.12]

    /// Peak accent and white coverage each style's pattern can reach.
    public static let patternDuty: [String: (amax: Double, wmax: Double)] = [
        "grid": (0.95, 0.05),
        "planes": (0.85, 0.3),
        "metal": (0.9, 0.5),
        "glyph": (0.15, 0.14),
        "orbit": (0.55, 0.3),
        "foil": (0.95, 0.12),
        "irid": (0.9, 0.55),
        "crest": (0.85, 0.26),
        "blob": (0.92, 0.93),
        "wave": (0.9, 0.95),
        "arc": (0.95, 0.05),
        "mesh": (0.95, 0.32),
        "confetti": (0.9, 0.8),
    ]
}
