import type { ArtStyle } from "@/lib/types";

export interface BankPreset {
  name: string;
  /** Base colour. */
  c1: string;
  /** Accent colour. */
  c2: string;
  style: ArtStyle;
  chip: boolean;
}

/**
 * Colour-and-pattern starting points named after the banks people actually carry, so a card
 * is recognisable at a glance in the deck.
 *
 * These are palettes and abstract patterns only. No issuer logo, wordmark or payment-network
 * mark is reproduced — those are trademarks, and cloning them would make the app
 * undistributable. The bank name is used descriptively to label the palette; everything the
 * user sees on the card is generated by this project's own art engine, and every value here
 * stays editable afterwards.
 */
export const BANK_PRESETS: readonly BankPreset[] = [
  // ── universal and commercial banks ──
  { name: "BPI", c1: "#8f1420", c2: "#3a070e", style: "planes", chip: true },
  { name: "BDO", c1: "#0b3b8c", c2: "#1f6fd0", style: "wave", chip: true },
  { name: "Metrobank", c1: "#4a2a6b", c2: "#8e5bb5", style: "planes", chip: true },
  { name: "RCBC", c1: "#12306e", c2: "#2f6fd0", style: "planes", chip: true },
  { name: "UnionBank", c1: "#141416", c2: "#c9a9ff", style: "irid", chip: true },
  { name: "Security Bank", c1: "#0057b8", c2: "#2f9ae0", style: "orbit", chip: true },
  { name: "Landbank", c1: "#0b5b2e", c2: "#5fbf6a", style: "wave", chip: true },
  { name: "EastWest", c1: "#b9cf00", c2: "#5c7a00", style: "planes", chip: true },
  { name: "Chinabank", c1: "#b8121b", c2: "#5e0709", style: "planes", chip: true },
  { name: "PNB", c1: "#0e7c7b", c2: "#6fd0cd", style: "orbit", chip: true },
  { name: "PSBank", c1: "#9aa4ae", c2: "#c8102e", style: "metal", chip: true },
  { name: "UCPB", c1: "#0075c9", c2: "#63c2f5", style: "wave", chip: true },
  { name: "DBP", c1: "#1b2c8c", c2: "#7b3fa0", style: "irid", chip: true },
  { name: "Maybank", c1: "#141414", c2: "#ffc72c", style: "planes", chip: true },
  { name: "PBCOM", c1: "#c8102e", c2: "#7a0a1c", style: "planes", chip: true },
  { name: "AUB", c1: "#f26522", c2: "#c8102e", style: "planes", chip: true },
  { name: "Bank of Commerce", c1: "#0b2c6b", c2: "#2f7fd0", style: "wave", chip: true },
  { name: "CTBC", c1: "#141414", c2: "#e60012", style: "orbit", chip: true },
  { name: "AllBank", c1: "#101828", c2: "#3f5a86", style: "grid", chip: true },
  { name: "BanKo", c1: "#e4002b", c2: "#ffffff", style: "confetti", chip: true },

  // ── e-wallets and digital banks ──
  { name: "GCash", c1: "#007dfe", c2: "#9fd4ff", style: "orbit", chip: false },
  { name: "Maya", c1: "#0f9d58", c2: "#7ef0b0", style: "orbit", chip: false },
  { name: "Cash", c1: "#f4eedc", c2: "#0b8f6a", style: "arc", chip: false },
];
