/* Generated by scripts/build-card-templates.mjs from APK. */
export const CARD_TEMPLATE_DATA = [
  {
    "id": "banks/template_001",
    "name": "All Bank Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_001.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      6,
      23,
      40
    ],
    "fallback": "#061728",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_002",
    "name": "AUB Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_002.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      131,
      9,
      2
    ],
    "fallback": "#830902",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_003",
    "name": "Bank Of Commerce Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_003.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      0,
      32,
      107
    ],
    "fallback": "#00206b",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_004",
    "name": "BDO",
    "category": "banks",
    "src": "/card-templates/banks/template_004.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      1,
      25,
      102
    ],
    "fallback": "#011966",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_005",
    "name": "BPI BanKo",
    "category": "banks",
    "src": "/card-templates/banks/template_005.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      144,
      4,
      24
    ],
    "fallback": "#900418",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_006",
    "name": "BPI",
    "category": "banks",
    "src": "/card-templates/banks/template_006.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      93,
      1,
      1
    ],
    "fallback": "#5d0101",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_007",
    "name": "China Bank Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_007.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      106,
      1,
      0
    ],
    "fallback": "#6a0100",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_008",
    "name": "China Bank Savings Atm",
    "category": "banks",
    "src": "/card-templates/banks/template_008.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      134,
      2,
      1
    ],
    "fallback": "#860201",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_009",
    "name": "Ctbc Bank Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_009.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      24,
      2,
      1
    ],
    "fallback": "#180201",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_010",
    "name": "DBP Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_010.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      27,
      5,
      99
    ],
    "fallback": "#1b0563",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_011",
    "name": "East West Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_011.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      191,
      198,
      5
    ],
    "fallback": "#bfc605",
    "scrim": "strong",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_012",
    "name": "LandBank Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_012.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      21,
      59,
      21
    ],
    "fallback": "#153b15",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_013",
    "name": "Maybank Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_013.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      49,
      39,
      13
    ],
    "fallback": "#31270d",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_014",
    "name": "Metrobank Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_014.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      61,
      23,
      80
    ],
    "fallback": "#3d1750",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_015",
    "name": "PBCOM Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_015.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      176,
      2,
      1
    ],
    "fallback": "#b00201",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_016",
    "name": "PNB Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_016.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      32,
      155,
      162
    ],
    "fallback": "#209ba2",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_017",
    "name": "PSBank Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_017.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      180,
      184,
      191
    ],
    "fallback": "#b4b8bf",
    "scrim": "strong",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_018",
    "name": "RCBC Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_018.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      1,
      33,
      99
    ],
    "fallback": "#012163",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_019",
    "name": "Security Bank Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_019.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      1,
      64,
      149
    ],
    "fallback": "#014095",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_020",
    "name": "UCPB Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_020.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      0,
      41,
      133
    ],
    "fallback": "#002985",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/template_021",
    "name": "Union Bank Debit",
    "category": "banks",
    "src": "/card-templates/banks/template_021.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      75,
      70,
      65
    ],
    "fallback": "#4b4641",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/template_022",
    "name": "BDO Gold Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/template_022.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      184,
      127,
      12
    ],
    "fallback": "#b87f0c",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/template_023",
    "name": "BDO Platinum Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/template_023.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      50,
      52,
      57
    ],
    "fallback": "#323439",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/template_024",
    "name": "BPI Gold Rewards Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/template_024.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      151,
      100,
      8
    ],
    "fallback": "#976408",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/template_025",
    "name": "BPI Platinum Rewards Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/template_025.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      110,
      115,
      124
    ],
    "fallback": "#6e737c",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/template_026",
    "name": "East West Gold Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/template_026.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      197,
      145,
      39
    ],
    "fallback": "#c59127",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/template_027",
    "name": "East West Platinum Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/template_027.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      74,
      75,
      79
    ],
    "fallback": "#4a4b4f",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/template_028",
    "name": "Maya Black Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/template_028.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      2,
      2,
      2
    ],
    "fallback": "#020202",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/template_029",
    "name": "Metrobank Gold Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/template_029.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      187,
      139,
      39
    ],
    "fallback": "#bb8b27",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/template_030",
    "name": "Metrobank Platinum Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/template_030.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      75,
      85,
      94
    ],
    "fallback": "#4b555e",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/template_031",
    "name": "RCBC Gold Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/template_031.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      176,
      129,
      31
    ],
    "fallback": "#b0811f",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/template_032",
    "name": "RCBC Platinum Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/template_032.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      29,
      47,
      69
    ],
    "fallback": "#1d2f45",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/template_033",
    "name": "Union Bank Platinum Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/template_033.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      205,
      237,
      226
    ],
    "fallback": "#cdede2",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "digital-banks/template_034",
    "name": "Cimb",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/template_034.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      133,
      27,
      49
    ],
    "fallback": "#851b31",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/template_035",
    "name": "Diskar Tech",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/template_035.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      80,
      191,
      149
    ],
    "fallback": "#50bf95",
    "scrim": "strong",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/template_036",
    "name": "Go Tyme",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/template_036.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      10,
      11,
      13
    ],
    "fallback": "#0a0b0d",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/template_037",
    "name": "Komo",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/template_037.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      79,
      213,
      231
    ],
    "fallback": "#4fd5e7",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/template_038",
    "name": "Mari Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/template_038.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      244,
      126,
      43
    ],
    "fallback": "#f47e2b",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/template_039",
    "name": "Netbank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/template_039.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      22,
      26,
      29
    ],
    "fallback": "#161a1d",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/template_040",
    "name": "Overseas Filipino Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/template_040.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      0,
      35,
      117
    ],
    "fallback": "#002375",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/template_041",
    "name": "Own Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/template_041.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      119,
      200,
      43
    ],
    "fallback": "#77c82b",
    "scrim": "strong",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/template_042",
    "name": "Salmon",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/template_042.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      246,
      108,
      95
    ],
    "fallback": "#f66c5f",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/template_043",
    "name": "Tonik",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/template_043.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      133,
      68,
      239
    ],
    "fallback": "#8544ef",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/template_044",
    "name": "Union Digital",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/template_044.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      171,
      150,
      233
    ],
    "fallback": "#ab96e9",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/template_045",
    "name": "Uno",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/template_045.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      12,
      8,
      14
    ],
    "fallback": "#0c080e",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/template_046",
    "name": "Zed",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/template_046.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      244,
      190,
      6
    ],
    "fallback": "#f4be06",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/template_047",
    "name": "Bayad",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/template_047.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      250,
      126,
      55
    ],
    "fallback": "#fa7e37",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/template_048",
    "name": "Cebuana Xpress",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/template_048.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      15,
      45,
      86
    ],
    "fallback": "#0f2d56",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/template_049",
    "name": "Coins Ph",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/template_049.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      49,
      111,
      251
    ],
    "fallback": "#316ffb",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/template_050",
    "name": "GCash",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/template_050.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      0,
      36,
      155
    ],
    "fallback": "#00249b",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/template_051",
    "name": "Grab Pay",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/template_051.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      39,
      209,
      99
    ],
    "fallback": "#27d163",
    "scrim": "strong",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/template_052",
    "name": "Luvit",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/template_052.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      25,
      45,
      10
    ],
    "fallback": "#192d0a",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/template_053",
    "name": "Maya",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/template_053.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      179,
      12,
      75
    ],
    "fallback": "#b30c4b",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/template_054",
    "name": "Ml Wallet",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/template_054.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      47,
      175,
      251
    ],
    "fallback": "#2faffb",
    "scrim": "strong",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/template_055",
    "name": "Palawan Pay",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/template_055.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      14,
      92,
      35
    ],
    "fallback": "#0e5c23",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/template_056",
    "name": "Pay Pal",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/template_056.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      1,
      48,
      143
    ],
    "fallback": "#01308f",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/template_057",
    "name": "Shopee Pay",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/template_057.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      251,
      94,
      7
    ],
    "fallback": "#fb5e07",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/template_058",
    "name": "Wise",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/template_058.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      169,
      210,
      21
    ],
    "fallback": "#a9d215",
    "scrim": "strong",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/template_059",
    "name": "7-Eleven Every Day Rewards",
    "category": "membership",
    "src": "/card-templates/membership/template_059.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      81,
      162,
      35
    ],
    "fallback": "#51a223",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/template_060",
    "name": "Bistro Group Membership",
    "category": "membership",
    "src": "/card-templates/membership/template_060.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      22,
      19,
      15
    ],
    "fallback": "#16130f",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/template_061",
    "name": "Laking National Bookstore Membership",
    "category": "membership",
    "src": "/card-templates/membership/template_061.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      221,
      11,
      20
    ],
    "fallback": "#dd0b14",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/template_062",
    "name": "Landers Membership",
    "category": "membership",
    "src": "/card-templates/membership/template_062.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      70,
      43,
      10
    ],
    "fallback": "#462b0a",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/template_063",
    "name": "Mercury Drug Membership",
    "category": "membership",
    "src": "/card-templates/membership/template_063.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      244,
      245,
      245
    ],
    "fallback": "#f4f5f5",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/template_064",
    "name": "Puregold Perks Membership",
    "category": "membership",
    "src": "/card-templates/membership/template_064.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      5,
      40,
      14
    ],
    "fallback": "#05280e",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/template_065",
    "name": "Robinsons Rewards Membership",
    "category": "membership",
    "src": "/card-templates/membership/template_065.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      184,
      12,
      2
    ],
    "fallback": "#b80c02",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/template_066",
    "name": "Smac Membership",
    "category": "membership",
    "src": "/card-templates/membership/template_066.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      0,
      63,
      168
    ],
    "fallback": "#003fa8",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "prepaid/template_067",
    "name": "Auto Sweep Rfid Prepaid",
    "category": "prepaid",
    "src": "/card-templates/prepaid/template_067.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      235,
      230,
      198
    ],
    "fallback": "#ebe6c6",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "prepaid/template_068",
    "name": "Beep Prepaid",
    "category": "prepaid",
    "src": "/card-templates/prepaid/template_068.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      33,
      37,
      87
    ],
    "fallback": "#212557",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "prepaid/template_069",
    "name": "Easytrip Prepaid",
    "category": "prepaid",
    "src": "/card-templates/prepaid/template_069.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      58,
      71,
      95
    ],
    "fallback": "#3a475f",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "prepaid/template_070",
    "name": "Starbucks Member Prepaid",
    "category": "prepaid",
    "src": "/card-templates/prepaid/template_070.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      1,
      50,
      24
    ],
    "fallback": "#013218",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  }
] as const;
