/* Generated by scripts/build-card-templates.mjs from Card_Backgrounds_WebP_By_Category. */
export const CARD_TEMPLATE_DATA = [
  {
    "id": "banks/amber-wave",
    "name": "Amber Wave",
    "category": "banks",
    "src": "/card-templates/banks/amber-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      190,
      185,
      34
    ],
    "fallback": "#beb922",
    "scrim": "strong",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/copper-wave",
    "name": "Copper Wave",
    "category": "banks",
    "src": "/card-templates/banks/copper-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      184,
      118,
      55
    ],
    "fallback": "#b87637",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/crimson-arc",
    "name": "Crimson Arc",
    "category": "banks",
    "src": "/card-templates/banks/crimson-arc.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      175,
      29,
      28
    ],
    "fallback": "#af1d1c",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/crimson-ridge",
    "name": "Crimson Ridge",
    "category": "banks",
    "src": "/card-templates/banks/crimson-ridge.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      142,
      23,
      23
    ],
    "fallback": "#8e1717",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/crimson-wave",
    "name": "Crimson Wave",
    "category": "banks",
    "src": "/card-templates/banks/crimson-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      158,
      35,
      45
    ],
    "fallback": "#9e232d",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/deep-blue-ridge",
    "name": "Deep Blue Ridge",
    "category": "banks",
    "src": "/card-templates/banks/deep-blue-ridge.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      23,
      50,
      120
    ],
    "fallback": "#173278",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/deep-blue-wave",
    "name": "Deep Blue Wave",
    "category": "banks",
    "src": "/card-templates/banks/deep-blue-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      34,
      56,
      117
    ],
    "fallback": "#223875",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/ember-ridge",
    "name": "Ember Ridge",
    "category": "banks",
    "src": "/card-templates/banks/ember-ridge.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      120,
      56,
      23
    ],
    "fallback": "#783817",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/ember-wave",
    "name": "Ember Wave",
    "category": "banks",
    "src": "/card-templates/banks/ember-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      137,
      56,
      39
    ],
    "fallback": "#893827",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/graphite-wave",
    "name": "Graphite Wave",
    "category": "banks",
    "src": "/card-templates/banks/graphite-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      76,
      76,
      81
    ],
    "fallback": "#4c4c51",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/indigo-wave",
    "name": "Indigo Wave",
    "category": "banks",
    "src": "/card-templates/banks/indigo-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      86,
      45,
      169
    ],
    "fallback": "#562da9",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/jade-wave",
    "name": "Jade Wave",
    "category": "banks",
    "src": "/card-templates/banks/jade-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      44,
      159,
      96
    ],
    "fallback": "#2c9f60",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/navy-ridge",
    "name": "Navy Ridge",
    "category": "banks",
    "src": "/card-templates/banks/navy-ridge.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      22,
      67,
      131
    ],
    "fallback": "#164383",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/navy-wave",
    "name": "Navy Wave",
    "category": "banks",
    "src": "/card-templates/banks/navy-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      34,
      68,
      128
    ],
    "fallback": "#224480",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/sapphire-ridge",
    "name": "Sapphire Ridge",
    "category": "banks",
    "src": "/card-templates/banks/sapphire-ridge.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      22,
      100,
      185
    ],
    "fallback": "#1664b9",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/sapphire-wave",
    "name": "Sapphire Wave",
    "category": "banks",
    "src": "/card-templates/banks/sapphire-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      34,
      97,
      188
    ],
    "fallback": "#2261bc",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/scarlet-ridge",
    "name": "Scarlet Ridge",
    "category": "banks",
    "src": "/card-templates/banks/scarlet-ridge.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      182,
      34,
      23
    ],
    "fallback": "#b62217",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/scarlet-wave",
    "name": "Scarlet Wave",
    "category": "banks",
    "src": "/card-templates/banks/scarlet-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      187,
      45,
      55
    ],
    "fallback": "#bb2d37",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/silver-wave",
    "name": "Silver Wave",
    "category": "banks",
    "src": "/card-templates/banks/silver-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      183,
      183,
      184
    ],
    "fallback": "#b7b7b8",
    "scrim": "strong",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/teal-wave",
    "name": "Teal Wave",
    "category": "banks",
    "src": "/card-templates/banks/teal-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      34,
      159,
      169
    ],
    "fallback": "#229fa9",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/violet-wave",
    "name": "Violet Wave",
    "category": "banks",
    "src": "/card-templates/banks/violet-wave.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      137,
      56,
      168
    ],
    "fallback": "#8938a8",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/copper-facet",
    "name": "Copper Facet",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/copper-facet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      185,
      120,
      59
    ],
    "fallback": "#b9783b",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/copper-prism",
    "name": "Copper Prism",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/copper-prism.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      185,
      121,
      53
    ],
    "fallback": "#b97935",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/graphite-facet",
    "name": "Graphite Facet",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/graphite-facet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      84,
      84,
      89
    ],
    "fallback": "#545459",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/graphite-prism",
    "name": "Graphite Prism",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/graphite-prism.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      84,
      90,
      94
    ],
    "fallback": "#545a5e",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/jade-facet",
    "name": "Jade Facet",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/jade-facet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      185,
      194,
      190
    ],
    "fallback": "#b9c2be",
    "scrim": "strong",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/navy-facet",
    "name": "Navy Facet",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/navy-facet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      59,
      70,
      99
    ],
    "fallback": "#3b4663",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/obsidian-facet",
    "name": "Obsidian Facet",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/obsidian-facet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      49,
      49,
      51
    ],
    "fallback": "#313133",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/pewter-facet",
    "name": "Pewter Facet",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/pewter-facet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      129,
      134,
      139
    ],
    "fallback": "#81868b",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/rust-facet",
    "name": "Rust Facet",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/rust-facet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      179,
      90,
      49
    ],
    "fallback": "#b35a31",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/rust-prism",
    "name": "Rust Prism",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/rust-prism.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      182,
      96,
      43
    ],
    "fallback": "#b6602b",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/slate-facet",
    "name": "Slate Facet",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/slate-facet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      119,
      130,
      140
    ],
    "fallback": "#77828c",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/terracotta-facet",
    "name": "Terracotta Facet",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/terracotta-facet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      187,
      130,
      69
    ],
    "fallback": "#bb8245",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "digital-banks/amber-pulse",
    "name": "Amber Pulse",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/amber-pulse.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      187,
      180,
      22
    ],
    "fallback": "#bbb416",
    "scrim": "strong",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/copper-pulse",
    "name": "Copper Pulse",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/copper-pulse.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      183,
      129,
      43
    ],
    "fallback": "#b7812b",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/crimson-pulse",
    "name": "Crimson Pulse",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/crimson-pulse.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      160,
      33,
      54
    ],
    "fallback": "#a02136",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/fern-pulse",
    "name": "Fern Pulse",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/fern-pulse.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      64,
      181,
      54
    ],
    "fallback": "#40b536",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/indigo-pulse",
    "name": "Indigo Pulse",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/indigo-pulse.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      117,
      55,
      187
    ],
    "fallback": "#7537bb",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/jade-pulse",
    "name": "Jade Pulse",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/jade-pulse.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      43,
      178,
      129
    ],
    "fallback": "#2bb281",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/midnight-pulse",
    "name": "Midnight Pulse",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/midnight-pulse.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      32,
      27,
      37
    ],
    "fallback": "#201b25",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/navy-pulse",
    "name": "Navy Pulse",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/navy-pulse.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      22,
      44,
      150
    ],
    "fallback": "#162c96",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/obsidian-pulse",
    "name": "Obsidian Pulse",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/obsidian-pulse.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      27,
      27,
      30
    ],
    "fallback": "#1b1b1e",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/onyx-pulse",
    "name": "Onyx Pulse",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/onyx-pulse.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      43,
      43,
      45
    ],
    "fallback": "#2b2b2d",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/scarlet-pulse",
    "name": "Scarlet Pulse",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/scarlet-pulse.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      186,
      65,
      65
    ],
    "fallback": "#ba4141",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/teal-pulse",
    "name": "Teal Pulse",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/teal-pulse.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      32,
      181,
      184
    ],
    "fallback": "#20b5b8",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/violet-pulse",
    "name": "Violet Pulse",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/violet-pulse.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      160,
      108,
      188
    ],
    "fallback": "#a06cbc",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/azure-ripple",
    "name": "Azure Ripple",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/azure-ripple.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      23,
      67,
      185
    ],
    "fallback": "#1743b9",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/cerulean-ripple",
    "name": "Cerulean Ripple",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/cerulean-ripple.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      44,
      178,
      191
    ],
    "fallback": "#2cb2bf",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/cobalt-ripple",
    "name": "Cobalt Ripple",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/cobalt-ripple.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      44,
      110,
      191
    ],
    "fallback": "#2c6ebf",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/copper-ripple",
    "name": "Copper Ripple",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/copper-ripple.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      187,
      120,
      44
    ],
    "fallback": "#bb782c",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/emerald-ripple",
    "name": "Emerald Ripple",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/emerald-ripple.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      34,
      142,
      66
    ],
    "fallback": "#228e42",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/fern-ripple",
    "name": "Fern Ripple",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/fern-ripple.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      33,
      99,
      45
    ],
    "fallback": "#21632d",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/jade-orbit",
    "name": "Jade Orbit",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/jade-orbit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      152,
      187,
      33
    ],
    "fallback": "#98bb21",
    "scrim": "strong",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/jade-ripple",
    "name": "Jade Ripple",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/jade-ripple.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      44,
      184,
      98
    ],
    "fallback": "#2cb862",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/navy-ripple",
    "name": "Navy Ripple",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/navy-ripple.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      34,
      56,
      109
    ],
    "fallback": "#22386d",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/plum-ripple",
    "name": "Plum Ripple",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/plum-ripple.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      173,
      34,
      109
    ],
    "fallback": "#ad226d",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/rust-ripple",
    "name": "Rust Ripple",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/rust-ripple.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      189,
      88,
      34
    ],
    "fallback": "#bd5822",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/sapphire-ripple",
    "name": "Sapphire Ripple",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/sapphire-ripple.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      23,
      78,
      179
    ],
    "fallback": "#174eb3",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/cobalt-halo",
    "name": "Cobalt Halo",
    "category": "membership",
    "src": "/card-templates/membership/cobalt-halo.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      32,
      94,
      185
    ],
    "fallback": "#205eb9",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/copper-halo",
    "name": "Copper Halo",
    "category": "membership",
    "src": "/card-templates/membership/copper-halo.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      134,
      84,
      42
    ],
    "fallback": "#86542a",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/crimson-halo",
    "name": "Crimson Halo",
    "category": "membership",
    "src": "/card-templates/membership/crimson-halo.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      183,
      43,
      47
    ],
    "fallback": "#b72b2f",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/fern-halo",
    "name": "Fern Halo",
    "category": "membership",
    "src": "/card-templates/membership/fern-halo.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      37,
      94,
      47
    ],
    "fallback": "#255e2f",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/jade-halo",
    "name": "Jade Halo",
    "category": "membership",
    "src": "/card-templates/membership/jade-halo.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      73,
      180,
      53
    ],
    "fallback": "#49b435",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/obsidian-halo",
    "name": "Obsidian Halo",
    "category": "membership",
    "src": "/card-templates/membership/obsidian-halo.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      47,
      47,
      47
    ],
    "fallback": "#2f2f2f",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/scarlet-halo",
    "name": "Scarlet Halo",
    "category": "membership",
    "src": "/card-templates/membership/scarlet-halo.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      185,
      48,
      37
    ],
    "fallback": "#b93025",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/silver-halo",
    "name": "Silver Halo",
    "category": "membership",
    "src": "/card-templates/membership/silver-halo.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      187,
      187,
      188
    ],
    "fallback": "#bbbbbc",
    "scrim": "strong",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "prepaid/amber-track",
    "name": "Amber Track",
    "category": "prepaid",
    "src": "/card-templates/prepaid/amber-track.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      191,
      189,
      181
    ],
    "fallback": "#bfbdb5",
    "scrim": "strong",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "prepaid/cobalt-track",
    "name": "Cobalt Track",
    "category": "prepaid",
    "src": "/card-templates/prepaid/cobalt-track.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      70,
      92,
      123
    ],
    "fallback": "#465c7b",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "prepaid/jade-track",
    "name": "Jade Track",
    "category": "prepaid",
    "src": "/card-templates/prepaid/jade-track.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      27,
      92,
      59
    ],
    "fallback": "#1b5c3b",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "prepaid/navy-track",
    "name": "Navy Track",
    "category": "prepaid",
    "src": "/card-templates/prepaid/navy-track.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      53,
      60,
      102
    ],
    "fallback": "#353c66",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  }
] as const;
