/* Generated by scripts/build-card-templates.mjs from Card_Backgrounds_WebP_By_Category 2. */
export const CARD_TEMPLATE_DATA = [
  {
    "id": "banks/all-bank-debit",
    "name": "AllBank Debit",
    "category": "banks",
    "src": "/card-templates/banks/all-bank-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      6,
      23,
      40
    ],
    "fallback": "#061728",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/aub-debit",
    "name": "AUB Debit",
    "category": "banks",
    "src": "/card-templates/banks/aub-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      131,
      9,
      2
    ],
    "fallback": "#830902",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/bank-of-commerce-debit",
    "name": "Bank of Commerce Debit",
    "category": "banks",
    "src": "/card-templates/banks/bank-of-commerce-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      0,
      32,
      107
    ],
    "fallback": "#00206b",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/bdo-debit",
    "name": "BDO Debit",
    "category": "banks",
    "src": "/card-templates/banks/bdo-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      1,
      25,
      102
    ],
    "fallback": "#011966",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/bpi-ban-ko-debit",
    "name": "BPI BanKo Debit",
    "category": "banks",
    "src": "/card-templates/banks/bpi-ban-ko-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      144,
      4,
      24
    ],
    "fallback": "#900418",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/bpi-debit",
    "name": "BPI Debit",
    "category": "banks",
    "src": "/card-templates/banks/bpi-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      93,
      1,
      1
    ],
    "fallback": "#5d0101",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/chinabank-debit",
    "name": "Chinabank Debit",
    "category": "banks",
    "src": "/card-templates/banks/chinabank-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      106,
      1,
      0
    ],
    "fallback": "#6a0100",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/chinabank-savings-atm",
    "name": "Chinabank Savings ATM",
    "category": "banks",
    "src": "/card-templates/banks/chinabank-savings-atm.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      134,
      2,
      1
    ],
    "fallback": "#860201",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/ctbc-bank-debit",
    "name": "CTBC Bank Debit",
    "category": "banks",
    "src": "/card-templates/banks/ctbc-bank-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      24,
      2,
      1
    ],
    "fallback": "#180201",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/dbp-debit",
    "name": "DBP Debit",
    "category": "banks",
    "src": "/card-templates/banks/dbp-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      27,
      5,
      99
    ],
    "fallback": "#1b0563",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/east-west-debit",
    "name": "EastWest Debit",
    "category": "banks",
    "src": "/card-templates/banks/east-west-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      191,
      198,
      5
    ],
    "fallback": "#bfc605",
    "scrim": "strong",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/landbank-debit",
    "name": "Landbank Debit",
    "category": "banks",
    "src": "/card-templates/banks/landbank-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      21,
      59,
      21
    ],
    "fallback": "#153b15",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/maybank-debit",
    "name": "Maybank Debit",
    "category": "banks",
    "src": "/card-templates/banks/maybank-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      49,
      39,
      13
    ],
    "fallback": "#31270d",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/metrobank-debit",
    "name": "Metrobank Debit",
    "category": "banks",
    "src": "/card-templates/banks/metrobank-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      61,
      23,
      80
    ],
    "fallback": "#3d1750",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/pbcom-debit",
    "name": "PBCOM Debit",
    "category": "banks",
    "src": "/card-templates/banks/pbcom-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      176,
      2,
      1
    ],
    "fallback": "#b00201",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/pnb-debit",
    "name": "PNB Debit",
    "category": "banks",
    "src": "/card-templates/banks/pnb-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      32,
      155,
      162
    ],
    "fallback": "#209ba2",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/psbank-debit",
    "name": "PSBank Debit",
    "category": "banks",
    "src": "/card-templates/banks/psbank-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      180,
      184,
      191
    ],
    "fallback": "#b4b8bf",
    "scrim": "strong",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/rcbc-debit",
    "name": "RCBC Debit",
    "category": "banks",
    "src": "/card-templates/banks/rcbc-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      1,
      33,
      99
    ],
    "fallback": "#012163",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/security-bank-debit",
    "name": "Security Bank Debit",
    "category": "banks",
    "src": "/card-templates/banks/security-bank-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      1,
      64,
      149
    ],
    "fallback": "#014095",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/ucpb-debit",
    "name": "UCPB Debit",
    "category": "banks",
    "src": "/card-templates/banks/ucpb-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      0,
      41,
      133
    ],
    "fallback": "#002985",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "banks/union-bank-debit",
    "name": "UnionBank Debit",
    "category": "banks",
    "src": "/card-templates/banks/union-bank-debit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      75,
      70,
      65
    ],
    "fallback": "#4b4641",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/bdo-gold-credit",
    "name": "BDO Gold Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/bdo-gold-credit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      184,
      127,
      12
    ],
    "fallback": "#b87f0c",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/bdo-platinum-credit",
    "name": "BDO Platinum Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/bdo-platinum-credit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      50,
      52,
      57
    ],
    "fallback": "#323439",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/bpi-gold-rewards-credit",
    "name": "BPI Gold Rewards Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/bpi-gold-rewards-credit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      151,
      100,
      8
    ],
    "fallback": "#976408",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/bpi-platinum-rewards-credit",
    "name": "BPI Platinum Rewards Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/bpi-platinum-rewards-credit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      110,
      115,
      124
    ],
    "fallback": "#6e737c",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/east-west-gold-credit",
    "name": "EastWest Gold Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/east-west-gold-credit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      197,
      145,
      39
    ],
    "fallback": "#c59127",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/east-west-platinum-credit",
    "name": "EastWest Platinum Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/east-west-platinum-credit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      74,
      75,
      79
    ],
    "fallback": "#4a4b4f",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/maya-black-credit",
    "name": "Maya Black Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/maya-black-credit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      2,
      2,
      2
    ],
    "fallback": "#020202",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/metrobank-gold-credit",
    "name": "Metrobank Gold Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/metrobank-gold-credit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      187,
      139,
      39
    ],
    "fallback": "#bb8b27",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/metrobank-platinum-credit",
    "name": "Metrobank Platinum Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/metrobank-platinum-credit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      75,
      85,
      94
    ],
    "fallback": "#4b555e",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/rcbc-gold-credit",
    "name": "RCBC Gold Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/rcbc-gold-credit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      176,
      129,
      31
    ],
    "fallback": "#b0811f",
    "scrim": "soft",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/rcbc-platinum-credit",
    "name": "RCBC Platinum Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/rcbc-platinum-credit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      29,
      47,
      69
    ],
    "fallback": "#1d2f45",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "credit-cards/union-bank-platinum-credit",
    "name": "UnionBank Platinum Credit",
    "category": "credit-cards",
    "src": "/card-templates/credit-cards/union-bank-platinum-credit.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      205,
      237,
      226
    ],
    "fallback": "#cdede2",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "digital-banks/cimb-digital-bank",
    "name": "CIMB Digital Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/cimb-digital-bank.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      133,
      27,
      49
    ],
    "fallback": "#851b31",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/diskar-tech-digital-bank",
    "name": "DiskarTech Digital Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/diskar-tech-digital-bank.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      80,
      191,
      149
    ],
    "fallback": "#50bf95",
    "scrim": "strong",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/go-tyme-digital-bank",
    "name": "GoTyme Digital Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/go-tyme-digital-bank.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      10,
      11,
      13
    ],
    "fallback": "#0a0b0d",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/komo-digital-bank",
    "name": "Komo Digital Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/komo-digital-bank.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      79,
      213,
      231
    ],
    "fallback": "#4fd5e7",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/mari-bank-digital-bank",
    "name": "MariBank Digital Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/mari-bank-digital-bank.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      244,
      126,
      43
    ],
    "fallback": "#f47e2b",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/netbank-digital-bank",
    "name": "Netbank Digital Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/netbank-digital-bank.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      22,
      26,
      29
    ],
    "fallback": "#161a1d",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/overseas-filipino-bank-digital-bank",
    "name": "Overseas Filipino Bank Digital Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/overseas-filipino-bank-digital-bank.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      0,
      35,
      117
    ],
    "fallback": "#002375",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/own-bank-digital-bank",
    "name": "OwnBank Digital Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/own-bank-digital-bank.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      119,
      200,
      43
    ],
    "fallback": "#77c82b",
    "scrim": "strong",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/salmon-digital-bank",
    "name": "Salmon Digital Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/salmon-digital-bank.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      246,
      108,
      95
    ],
    "fallback": "#f66c5f",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/tonik-digital-bank",
    "name": "Tonik Digital Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/tonik-digital-bank.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      133,
      68,
      239
    ],
    "fallback": "#8544ef",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/union-digital-digital-bank",
    "name": "UnionDigital Digital Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/union-digital-digital-bank.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      171,
      150,
      233
    ],
    "fallback": "#ab96e9",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/uno-digital-bank",
    "name": "UNO Digital Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/uno-digital-bank.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      12,
      8,
      14
    ],
    "fallback": "#0c080e",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "digital-banks/zed-digital-bank",
    "name": "Zed Digital Bank",
    "category": "digital-banks",
    "src": "/card-templates/digital-banks/zed-digital-bank.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      244,
      190,
      6
    ],
    "fallback": "#f4be06",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/bayad-ewallet",
    "name": "Bayad E-wallet",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/bayad-ewallet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      250,
      126,
      55
    ],
    "fallback": "#fa7e37",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/cebuana-xpress-ewallet",
    "name": "Cebuana Xpress E-wallet",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/cebuana-xpress-ewallet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      15,
      45,
      86
    ],
    "fallback": "#0f2d56",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/coins-ph-ewallet",
    "name": "Coins.ph E-wallet",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/coins-ph-ewallet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      49,
      111,
      251
    ],
    "fallback": "#316ffb",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/gcash-ewallet",
    "name": "GCash E-wallet",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/gcash-ewallet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      0,
      36,
      155
    ],
    "fallback": "#00249b",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/grab-pay-ewallet",
    "name": "GrabPay E-wallet",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/grab-pay-ewallet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      39,
      209,
      99
    ],
    "fallback": "#27d163",
    "scrim": "strong",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/luvit-ewallet",
    "name": "Luvit E-wallet",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/luvit-ewallet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      25,
      45,
      10
    ],
    "fallback": "#192d0a",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/maya-ewallet",
    "name": "Maya E-wallet",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/maya-ewallet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      179,
      12,
      75
    ],
    "fallback": "#b30c4b",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/ml-wallet-ewallet",
    "name": "ML Wallet E-wallet",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/ml-wallet-ewallet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      47,
      175,
      251
    ],
    "fallback": "#2faffb",
    "scrim": "strong",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/palawan-pay-ewallet",
    "name": "PalawanPay E-wallet",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/palawan-pay-ewallet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      14,
      92,
      35
    ],
    "fallback": "#0e5c23",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/pay-pal-ewallet",
    "name": "PayPal E-wallet",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/pay-pal-ewallet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      1,
      48,
      143
    ],
    "fallback": "#01308f",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/shopee-pay-ewallet",
    "name": "ShopeePay E-wallet",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/shopee-pay-ewallet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      251,
      94,
      7
    ],
    "fallback": "#fb5e07",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "e-wallets/wise-ewallet",
    "name": "Wise E-wallet",
    "category": "e-wallets",
    "src": "/card-templates/e-wallets/wise-ewallet.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      169,
      210,
      21
    ],
    "fallback": "#a9d215",
    "scrim": "strong",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/7eleven-every-day-rewards",
    "name": "7-Eleven Every Day Rewards",
    "category": "membership",
    "src": "/card-templates/membership/7eleven-every-day-rewards.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      81,
      162,
      35
    ],
    "fallback": "#51a223",
    "scrim": "soft",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/bistro-group-membership",
    "name": "Bistro Group Membership",
    "category": "membership",
    "src": "/card-templates/membership/bistro-group-membership.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      22,
      19,
      15
    ],
    "fallback": "#16130f",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/laking-national-bookstore-membership",
    "name": "Laking National Bookstore Membership",
    "category": "membership",
    "src": "/card-templates/membership/laking-national-bookstore-membership.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      221,
      11,
      20
    ],
    "fallback": "#dd0b14",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/landers-membership",
    "name": "Landers Membership",
    "category": "membership",
    "src": "/card-templates/membership/landers-membership.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      70,
      43,
      10
    ],
    "fallback": "#462b0a",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/mercury-drug-membership",
    "name": "Mercury Drug Membership",
    "category": "membership",
    "src": "/card-templates/membership/mercury-drug-membership.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      244,
      245,
      245
    ],
    "fallback": "#f4f5f5",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/puregold-perks-membership",
    "name": "Puregold Perks Membership",
    "category": "membership",
    "src": "/card-templates/membership/puregold-perks-membership.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      5,
      40,
      14
    ],
    "fallback": "#05280e",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/robinsons-rewards-membership",
    "name": "Robinsons Rewards Membership",
    "category": "membership",
    "src": "/card-templates/membership/robinsons-rewards-membership.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      184,
      12,
      2
    ],
    "fallback": "#b80c02",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "membership/smac-membership",
    "name": "SMAC Membership",
    "category": "membership",
    "src": "/card-templates/membership/smac-membership.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      0,
      63,
      168
    ],
    "fallback": "#003fa8",
    "scrim": "off",
    "textMode": "auto",
    "chip": false
  },
  {
    "id": "prepaid/auto-sweep-rfid-prepaid",
    "name": "AutoSweep RFID Prepaid",
    "category": "prepaid",
    "src": "/card-templates/prepaid/auto-sweep-rfid-prepaid.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      235,
      230,
      198
    ],
    "fallback": "#ebe6c6",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "prepaid/beep-prepaid",
    "name": "Beep Prepaid",
    "category": "prepaid",
    "src": "/card-templates/prepaid/beep-prepaid.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      33,
      37,
      87
    ],
    "fallback": "#212557",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "prepaid/easytrip-prepaid",
    "name": "Easytrip Prepaid",
    "category": "prepaid",
    "src": "/card-templates/prepaid/easytrip-prepaid.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      58,
      71,
      95
    ],
    "fallback": "#3a475f",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  },
  {
    "id": "prepaid/starbucks-member-prepaid",
    "name": "Starbucks Member Prepaid",
    "category": "prepaid",
    "src": "/card-templates/prepaid/starbucks-member-prepaid.webp",
    "focal": [
      0,
      0
    ],
    "sample": [
      1,
      50,
      24
    ],
    "fallback": "#013218",
    "scrim": "off",
    "textMode": "auto",
    "chip": true
  }
] as const;
