/*
 * Generates ios/Pesolita/Pesolita/DesignSystem/Tokens.swift from the web app's own sources.
 *
 * The iOS port has to match the web design exactly, and the surface is too wide to
 * transcribe by hand: ~60 custom properties, six palettes, eight category colours and
 * several tables the contrast tuner depends on. Transcription drifts the moment either
 * side is edited; generation cannot. Run this after touching globals.css or constants.ts.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(resolve(root, p), "utf8");

const css = read("app/globals.css");
const constants = read("lib/constants.ts");
const legibility = read("lib/legibility.ts");

/** The `:root` block is the whole token surface; nothing else declares custom properties. */
const rootBlock = css.match(/:root\s*\{([\s\S]*?)\n\}/);
if (!rootBlock) throw new Error("globals.css: no :root block found");

const decls = [...rootBlock[1].matchAll(/^\s*(--[\w-]+):\s*([^;]+);/gm)].map(([, name, value]) => ({
  name,
  value: value.trim(),
}));

const camel = (name) => name.replace(/^--/, "").replace(/-(\w)/g, (_, c) => c.toUpperCase());

const colors = decls.filter((d) => /^#[0-9a-f]{6}$/i.test(d.value));
const eases = decls.filter((d) => d.value.startsWith("cubic-bezier"));
// Plain px lengths only. calc()/env() tokens are safe-area maths that SwiftUI expresses
// natively through safeAreaInsets, so carrying them over as numbers would be misleading.
const lengths = decls.filter((d) => /^\d+(\.\d+)?px$/.test(d.value));

const pairs = (block) => [...block.matchAll(/\["(#[0-9a-f]{6})",\s*"(#[0-9a-f]{6})"\]/gi)];
const palettes = pairs(constants.match(/PALETTES[^=]*=\s*\[([\s\S]*?)\n\];/)[1]);

const categories = [
  ...constants.match(/CATEGORIES[^=]*=\s*\[([\s\S]*?)\n\];/)[1].matchAll(
    /\{\s*name:\s*"([^"]+)",\s*color:\s*"(#[0-9a-f]{6})"\s*\}/gi,
  ),
];

const scrim = [
  ...constants.match(/SCRIM:\s*Record<ScrimKey,\s*number>\s*=\s*\{([\s\S]*?)\n\};/)[1].matchAll(
    /(\w+):\s*([\d.]+)/g,
  ),
];

const duty = [
  ...constants.match(/PATTERN_DUTY[^=]*=\s*\{([\s\S]*?)\n\};/)[1].matchAll(
    /(\w+):\s*\{\s*amax:\s*([\d.]+),\s*wmax:\s*([\d.]+)\s*\}/g,
  ),
];

const amplitudes = legibility
  .match(/AMPLITUDES\s*=\s*\[([^\]]+)\]/)[1]
  .split(",")
  .map((n) => n.trim());

const num = (key) => constants.match(new RegExp(`export const ${key} = (\\d+);`))[1];

const swiftColor = (hex) => {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
  return `Color(red: ${(r / 255).toFixed(4)}, green: ${(g / 255).toFixed(4)}, blue: ${(b / 255).toFixed(4)})`;
};

const bezier = (value) => value.match(/cubic-bezier\(([^)]+)\)/)[1].split(",").map((n) => n.trim());

const out = [];
const w = (line = "") => out.push(line);

w("// Generated by tools/export-tokens.mjs — do not edit by hand.");
w("// Source: app/globals.css, lib/constants.ts, lib/legibility.ts");
w("// Regenerate with: npm run tokens:ios");
w("");
w("import SwiftUI");
w("");
w("/// The web app's design tokens, verbatim. CSS pixels map 1:1 to iOS points.");
w("public enum Tokens {");

w("    // MARK: - Color");
w("");
for (const c of colors) w(`    public static let ${camel(c.name)} = ${swiftColor(c.value)}`);

w("");
w("    // MARK: - Motion");
w("");
w("    /// Durations come from the call site because CSS carries them on each declaration,");
w("    /// not on the easing token.");
for (const e of eases) {
  const [a, b, c, d] = bezier(e.value);
  w(`    public static func ${camel(e.name)}(_ duration: Double) -> Animation {`);
  w(`        .timingCurve(${a}, ${b}, ${c}, ${d}, duration: duration)`);
  w("    }");
}
w("");
w("    /// Literal curves used outside the two named tokens.");
w("    public static func dealCurve(_ duration: Double) -> Animation {");
w("        .timingCurve(0.2, 0.9, 0.22, 1, duration: duration)");
w("    }");
w("");
w("    public static func flipCurve(_ duration: Double) -> Animation {");
w("        .timingCurve(0.22, 1, 0.28, 1, duration: duration)");
w("    }");

w("");
w("    // MARK: - Layout");
w("");
for (const l of lengths) w(`    public static let ${camel(l.name)}: CGFloat = ${parseFloat(l.value)}`);

w("");
w("    // MARK: - Card geometry");
w("");
w("    /// The art engine is authored against this box; every size scales off the width.");
for (const key of ["CARD_W", "CARD_H", "CARD_R", "DECK_STEP", "DECK_ORIGIN"]) {
  w(`    public static let ${camel("--" + key.toLowerCase().replace(/_/g, "-"))}: CGFloat = ${num(key)}`);
}

w("");
w("    // MARK: - Card palettes");
w("");
w("    public static let palettes: [(base: Color, accent: Color)] = [");
for (const [, base, accent] of palettes) w(`        (${swiftColor(base)}, ${swiftColor(accent)}),`);
w("    ]");

w("");
w("    // MARK: - Category colors");
w("");
w("    public static let categoryColors: [String: Color] = [");
for (const [, name, hex] of categories) w(`        "${name}": ${swiftColor(hex)},`);
w("    ]");

w("");
w("    // MARK: - Legibility tuner tables");
w("");
w("    /// Scrim ladder — alpha of the wash behind card text.");
w("    public static let scrim: [String: Double] = [");
for (const [, key, value] of scrim) w(`        "${key}": ${value},`);
w("    ]");
w("");
w("    /// Pattern amplitudes the tuner damps through, strongest first.");
w(`    public static let amplitudes: [Double] = [${amplitudes.join(", ")}]`);
w("");
w("    /// Peak accent and white coverage each style's pattern can reach.");
w("    public static let patternDuty: [String: (amax: Double, wmax: Double)] = [");
for (const [, style, amax, wmax] of duty) w(`        "${style}": (${amax}, ${wmax}),`);
w("    ]");

w("}");
w("");

const dest = resolve(root, "ios/Pesolita/Pesolita/DesignSystem/Tokens.swift");
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, out.join("\n"));

console.log(
  `Tokens.swift: ${colors.length} colors, ${eases.length} easings, ${lengths.length} lengths, ` +
    `${palettes.length} palettes, ${categories.length} categories, ${duty.length} duty rows`,
);
